Updating integration to handle third possible integer as 'optional'.
segment-integrations/analytics-ios-integration-taplytics pull request #7
Opened 2016-10-04 14:13 UTC by VicV

Currently, Segment does not support sending down a 'null' value for options that have a 'default' setting (or rather, it can either be true or false or the system will decide it).

I've changed it around to accept 0,1,2 as the values, which map to an enumerator containing On/Off/Default. The taplytics SDK will handle this accordingly. 

Changed setting names to expect _V2 for these.

2016-10-11 14:33 UTC, VicV commented
@f2prateek timeline on this one?

2016-10-11 17:06 UTC, f2prateek commented
Ah sorry I didn't see this until now. I'll take a look today.

2016-10-11 23:23 UTC, f2prateek requested changes

2016-10-11 23:23 UTC, f2prateek commented on Segment-Taplytics/Classes/SEGTaplyticsIntegration.m
> +- (NSNumber *)shakeMenuV2
We're sending a string from our servers not a number.

2016-10-11 23:26 UTC, VicV commented
Ah, my bad! I'll switch it up tomorrow

On Oct 11, 2016 7:23 PM, "Prateek Srivastava" <notifications@github.com>
wrote:

> *@f2prateek* requested changes on this pull request.
> ------------------------------
>
> In Segment-Taplytics/Classes/SEGTaplyticsIntegration.m
> <https://github.com/segment-integrations/analytics-ios-integration-taplytics/pull/7#pullrequestreview-3784369>
> :
>
> > @@ -168,11 +173,17 @@ - (NSNumber *)taplyticsOptionSessionBackgroundTime
>      return (NSNumber *)[self.settings objectForKey:@"sessionMinutes"];
>  }
>
> -- (NSNumber *)shakeMenu
> +- (NSNumber *)liveUpdateV2
> +{
> +    return (NSNumber *)[self.settings objectForKey:@"liveUpdate_v2"];
> +}
> +
> +- (NSNumber *)shakeMenuV2
>
> We're sending a string from our servers not a number.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/segment-integrations/analytics-ios-integration-taplytics/pull/7#pullrequestreview-3784369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABPbJTrtxRpT-AJW2PHBARo-OG7gYuRbks5qzBqFgaJpZM4KNuhB>
> .
>

2016-10-12 03:40 UTC, f2prateek commented
Cool, and just to confirm, the strings are "true", "false" or "default".

2016-10-17 20:39 UTC, VicV commented
@f2prateek sorry for the delay, should be good to go. Take a look.

2016-10-18 14:53 UTC, VicV commented
@f2prateek Any chance you could take a look at this today? Need to know the timeline for a client.

2016-10-18 18:14 UTC, f2prateek commented on Segment-Taplytics/Classes/SEGTaplyticsIntegration.m
>          SEGLog(@"[[Taplytics startTaplyticsAPIKey:%@ options:%@]]", apiKey, settings);
This should be changed to `options` as well.

2016-10-18 18:14 UTC, f2prateek commented
@VicV CI is failing, needs to be fixed before we can merge.

2016-10-18 19:37 UTC, VicV commented
@f2prateek not 100% sure what the checks were failing on. Ran a pod update and sent it up. How long do these take to run?

2016-10-18 20:00 UTC, f2prateek commented
These took about 30seconds from what I can tell https://travis-ci.org/segment-integrations/analytics-ios-integration-taplytics/builds/168721285

https://cloudup.com/cgjO99d2vQQ

2016-10-18 20:05 UTC, VicV commented
@f2prateek I don't know what any of those failures are given that I didn't write this integration.

2016-10-18 20:11 UTC, f2prateek commented
From what I can tell, something in your changes is breaking the CI. Are you able to build locally?

2016-10-18 20:15 UTC, VicV commented
@f2prateek yep, no issues.

2016-10-18 20:19 UTC, f2prateek commented
Ok i'll run it locally and see what's up.

btw this is missing new tests.

2016-10-18 20:33 UTC, f2prateek commented
(I'll add the tests)

2016-10-18 20:57 UTC, f2prateek commented
Closed by #8

2016-10-18 20:57 UTC, closed without merging

2016-10-18 21:08 UTC, f2prateek commented
1.1.0 with these changes is out now.